<?php

function triangles_menu() {
  $items = array();
  $items['triangle_calculator'] = array(
    'title' => 'Triangle Calculator',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('triangle_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  $items['triangle_success'] = array(
    'title' => 'Success',
    'page callback' => 'triangle_success',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function triangle_form() {
  $form = array();
  $form['side_one'] = array(
    '#title' => 'Side One',
    '#type' => 'textfield',
    '#description' => t('Enter the length of side one.'),
    '#element_validate' => array('element_validate_number', 'element_validate_positive_float'),
    '#required' => TRUE,
  );

  $form['side_two'] = array(
    '#title' => 'Side Two',
    '#type' => 'textfield',
    '#description' => t('Enter the length of side two.'),
    '#element_validate' => array('element_validate_number', 'element_validate_positive_float'),
    '#required' => TRUE,
  );

  $form['side_three'] = array(
    '#title' => 'Side Three',
    '#type' => 'textfield',
    '#description' => t('Enter the length of side three.'),
    '#element_validate' => array('element_validate_number', 'element_validate_positive_float'),
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'What kind of triangle am I???',
  );

  return $form;
}


function element_validate_positive_float($element) {
  if ($element['#value'] <= 0) {
    form_error($element, t('Number must be positive.'));
  }
}

function triangle_form_submit($form, &$form_state) {
  $side_one = $form_state['values']['side_one'];
  $side_two = $form_state['values']['side_two'];
  $side_three = $form_state['values']['side_three'];
  if($side_one == $side_two && $side_two == $side_three) {
    $_SESSION['triangle_result'] = '<p>What a dreamy equilateral triangle.</p>';
  } elseif($side_one == $side_two || $side_two == $side_three || $side_three == $side_one) {
    $_SESSION['triangle_result'] = '<p>Isosceles triangle.</p>';
  } elseif($side_one != $side_two && $side_one != $side_three && $side_two != $side_three) {
    $_SESSION['triangle_result'] = '<p>Scalene triangle.</p>';
  }
  $form_state['redirect'] = 'triangle_success';
}

function triangle_success() {
  $answer = $_SESSION['triangle_result'];
  return $answer;
}
