<?php

function title_case_menu() {
  $items = array();
  $items['title_case'] = array(
    'title' => 'CONVERSION',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('title_case_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['title_case_success_page'] = array(
    'title' => 'Great Success',
    'page callback' => 'title_case_success',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}


function title_case_form() {
  $form['input_string'] = array(
    '#title' => 'Phrase',
    '#type' => 'textfield',
    '#description' => t('Whaddaya want to translate into title case?! Isn\'t this great?'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Translate!',
  );

  return $form;
}


function title_case_form_submit($form, &$form_state) {
  $input_string = $form_state['values']['input_string'];
  $output_string = "";

  foreach (explode(' ', $input_string) as $word) {
    $output_string .= (ucfirst(strtolower($word)) . ' ');
  }

  $_SESSION['title_case_output'] = $output_string;
  $form_state['redirect'] = 'title_case_success_page';
}


function title_case_success() {
  $output = '<h1>' . $_SESSION['title_case_output'] . '</h1>';
  return "Titled Cased: $output";
}
