<?php

function queen_attack_menu() {
  $items = array();
  $items['queen_attack'] = array(
    'title' => 'Queen Attack Entry Form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('queen_attack_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  $items['queen_attack_success_page'] = array(
    'title' => 'Queen Attack Results',
    'page callback' => 'queen_attack_success',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}




function queen_attack_form() {
  $coordinate_options = array(
    0 => 0,
    1 => 1,
    2 => 2,
    3 => 3,
    4 => 4,
    5 => 5,
    6 => 6,
    7 => 7,
  );

  $coordinate_options_alpha = array(
    0 => "a",
    1 => "b",
    2 => "c",
    3 => "d",
    4 => "e",
    5 => "f",
    6 => "g",
    7 => "h"
  );


  // Select usage is a bit different than this, see FORM API
  $form['queen_x_coordinate'] = array(
    '#title' => 'Queen x coordinate',
    '#type' => 'select',
    '#options' => $coordinate_options,
    '#description' => t('Set the Queen\'s X coordinate.'),
  );

  $form['queen_y_coordinate'] = array(
    '#title' => 'Queen y coordinate',
    '#type' => 'select',
    '#options' => $coordinate_options_alpha,
    '#description' => t('Set the Queen\'s Y coordinate.'),
  );

  $form['piece_x_coordinate'] = array(
    '#title' => 'Piece x coordinate',
    '#type' => 'select',
    '#options' => $coordinate_options,
    '#description' => t('Set the Piece\'s X coordinate.'),
  );

  $form['piece_y_coordinate'] = array(
    '#title' => 'Piece y coordinate',
    '#type' => 'select',
    '#options' => $coordinate_options_alpha,
    '#description' => t('Set the Piece\'s Y coordinate.'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Activate this incredibly useful module!',
  );

  return $form;
}

function queen_attack_form_submit($form, &$form_state) {
  $queen_x = $form_state['values']['queen_x_coordinate'];
  $queen_y = $form_state['values']['queen_y_coordinate'];
  $piece_x = $form_state['values']['piece_x_coordinate'];
  $piece_y = $form_state['values']['piece_y_coordinate'];

  // Calculate difference between two pieces in each plane.
  // Use absolute value to avoid negative distances.
  $diff_x = abs($queen_x - $piece_x);
  $diff_y = abs($queen_y - $piece_y);

  if (($queen_x == $piece_x) || ($queen_y == $piece_y) || ($diff_x == $diff_y)) {
    $_SESSION['queen_result'] = true;
  } else {
    $_SESSION['queen_result'] = false;
  }

  $form_state['redirect'] = 'queen_attack_success_page';
}


function queen_attack_success() {
  $output = '<h1>';
  if ($_SESSION['queen_result']) {
    $output .= "WINNNNN";
  } else {
    $output .= "LOOOOOOOOSE";
  }

  $output .= '</h1>';
  return "Attacked? $output";
}
